### ISSUE TITLE
Add option to not guess project dir

### ISSUE THREAD

**Issue by daliusd** [ddrscott/vim-side-search#12]
I'm working on huge monorepo and usually want to work on limited scope. This plugin tries to guess root folder and search from it what hits performance.

**Comment by daliusd** [comment]
I see newest change from @jakutis allows me to add this to my config and be happy with it:
```
function! FindRootDirectory()
  return getcwd()
endfunction
```

Maybe this can be added to documentation.

**Comment by ddrscott** [comment]
I didn't even realize these were 2 separate requests 😬 

Yeah, adding the `FindRootDirectory` function seems to be a good option. It clobbers Airblades function a little bit, but overall, I think it's okay since the intent of the function is to find the project's root and if your specific use case is answered by `getcwd` it makes sense to me.

I'll add something to the README and the Vim help.
